language: node_js
sudo: false
node_js: "stable"
install: npm install
before_script: npm install grunt-cli -g
env:
  matrix:
    - BROWSER=chromium EXT=zip
script:
  - npm test
  - bash ./scripts/build-${BROWSER}.sh
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_OAUTH_TOKEN
  file: h8blck-${BROWSER}.${EXT}
  skip_cleanup: true
  on:
    repo: qtpham1998/h8bl-ck
    tags: true
    branches:
      only:
        - master